{"name": "test_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 < 1", "trace": "def test_03():\n>       assert 2 < 1\nE       assert 2 < 1\n\ntest_case.py:20: AssertionError"}, "start": 1617812461238, "stop": 1617812461238, "uuid": "cd1620c0-0908-4566-a5b6-fce68c0ba842", "historyId": "5c1cb06c1153d91e2e23f5f3ccf9466d", "testCaseId": "772ee26b921bb8752ea8a976ba718c29", "fullName": "test_case#test_03", "labels": [{"name": "suite", "value": "test_case"}, {"name": "host", "value": "DESKTOP-5SVAUJU"}, {"name": "thread", "value": "1876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case"}]}